spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/customers?allowPublicKeyRetrieval=true&useSSL=false
    username: customers
    password: customers1
    initialization-mode: always
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:31663/eureka